import { Project } from "./columns";

export const data: Project[] = [
  {
    id: "1",
    title: "Portfolio Website",
    description: "Personal portfolio built with Next.js",
    content: "Showcases projects, skills, and contact information.",
    tags: "Next.js, Tailwind, Shadcn",
    isPublished: true,
  },
  {
    id: "2",
    title: "E-commerce App",
    description: "Online book store",
    content: "Users can browse books, add to cart, and checkout.",
    tags: "React, Node.js, MongoDB",
    isPublished: true,
  },
  {
    id: "3",
    title: "Meow Meow",
    description: "Woof Woof Arf Arf",
    content: "Includes charts, categories, and monthly summaries.",
    tags: "Vue, Express, MySQL",
    isPublished: true,
  },
  {
    id: "4",
    title: "Static Project",
    description: "Static Project Meow Meow",
    content: "Handles reservations, payments, and reports.",
    tags: "Java, Selenium, TestNG",
    isPublished: false,
  },
  {
    id: "5",
    title: "Static Project",
    description: "Mobile app with admin portal",
    content:
      "Connects customers with local service providers. Includes booking, real-time tracking, ratings, and an admin dashboard for managing providers and services.",
    tags: "Flutter, Spring Boot, PostgreSQL, Prisma",
    isPublished: true,
  },
  // {
  //   id: "6",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "7",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "8",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "9",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "10",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "11",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
  // {
  //   id: "12",
  //   title: "Personal Portfolio",
  //   description: "This portfolio website",
  //   content: "A modern, animated portfolio with dark mode, glassmorphism cards, project showcase with pagination, and a contact section.",
  //   tags: "Next.js, Tailwind CSS, Shadcn, TypeScript",
  //   isPublished: true,
  // },
];
